# -*- coding: utf-8 -*-
"""nfhs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EzN2UG5n3B0J-hQlzbLiX_OpJIEFZoJV
"""

import sys
!{sys.executable} -m pip install streamlit pandas plotly-express

import streamlit as st
import pandas as pd
import plotly.express as px

# Page configuration
st.set_page_config(page_title="NFHS Dashboard", layout="wide")

st.title("📊 National Family Health Survey (NFHS) Dashboard")
st.markdown("Interactive dashboard for exploring NFHS data")

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv("/content/All India National Family Health Survey.csv")
    return df

df = load_data()

# Sidebar Filters
st.sidebar.header("🔎 Filters")

# Show columns
st.sidebar.subheader("Select Columns to Analyze")
numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_columns = df.select_dtypes(include=['object']).columns.tolist()

selected_numeric = st.sidebar.selectbox("Select Numeric Indicator", numeric_columns)

if categorical_columns:
    selected_category = st.sidebar.selectbox("Select Category (State/Year/etc)", categorical_columns)
    category_values = st.sidebar.multiselect(
        f"Filter {selected_category}",
        df[selected_category].unique(),
        default=df[selected_category].unique()
    )
    df = df[df[selected_category].isin(category_values)]

# Main Layout
col1, col2 = st.columns(2)

# KPI Section
with col1:
    st.subheader("📌 Key Statistics")
    st.metric("Average", round(df[selected_numeric].mean(), 2))
    st.metric("Maximum", round(df[selected_numeric].max(), 2))
    st.metric("Minimum", round(df[selected_numeric].min(), 2))

# Bar Chart
with col2:
    if categorical_columns:
        st.subheader("📊 Bar Chart")
        fig_bar = px.bar(
            df,
            x=selected_category,
            y=selected_numeric,
            color=selected_category,
            title=f"{selected_numeric} by {selected_category}"
        )
        st.plotly_chart(fig_bar, use_container_width=True)

# Line Chart (if time-related column exists)
time_columns = [col for col in categorical_columns if "year" in col.lower()]
if time_columns:
    st.subheader("📈 Trend Analysis")
    time_col = time_columns[0]
    fig_line = px.line(
        df,
        x=time_col,
        y=selected_numeric,
        color=selected_category if categorical_columns else None,
        markers=True,
        title=f"{selected_numeric} Trend Over Time"
    )
    st.plotly_chart(fig_line, use_container_width=True)

# Data Table
st.subheader("📄 Data Preview")
st.dataframe(df.head(100))

# Download Option
st.download_button(
    label="Download Filtered Data as CSV",
    data=df.to_csv(index=False),
    file_name="filtered_nfhs_data.csv",
    mime="text/csv"
)